export const ADD_PROPERTY = 'company/ADD_PROPERTY';
export const TOGGLE_ADD_PROPERTY_MODAL = 'company/OPEN_ADD_PROPERTY_MODAL';
export const FETCH_PROPERTIES = 'company/FETCH_PROPERTIES';
export const PROPERTIES_FETCHED = 'company/PROPERTIES_FETCHED'; 
export const UPDATE_NEW_PROPERTY = 'company/UPDATE_NEW_PROPERTY';