export const FETCH_ASSET = 'asset/FETCH_ASSET';
export const ASSET_FETCHED = 'asset/ASSET_FETCHED'; 

export const TOGGLE_ADD_BOOKING_MODAL = 'asset/OPEN_ADD_BOOKING_MODAL';
export const UPDATE_NEW_BOOKING = 'asset/UPDATE_NEW_BOOKING';
export const ADD_BOOKING = 'asset/ADD_BOOKING';

export const TOGGLE_MANAGE_ASSET_MODAL = 'asset/OPEN_MANAGE_ASSET_MODAL';
export const UPDATE_MANAGE_ASSET = 'asset/UPDATE_MANAGE_ASSET';
export const UPDATE_MANAGE_ASSET_ADD_AMENITY = 'asset/UPDATE_MANAGE_ASSET_ADD_AMENITY';
export const UPDATE_MANAGE_ASSET_REMOVE_AMENITY = 'asset/UPDATE_MANAGE_ASSET_REMOVE_AMENITY';
export const SAVE_ASSET = 'asset/SAVE_ASSET';