export const FETCH_ASSETS = 'property/FETCH_ASSETS';
export const ASSETS_FETCHED = 'property/ASSETS_FETCHED';

export const FETCH_PROPERTY = 'property/FETCH_PROPERTY';
export const PROPERTY_FETCHED = 'property/PROPERTY_FETCHED'; 

export const TOGGLE_ADD_ASSET_MODAL = 'property/OPEN_ADD_ASSET_MODAL';
export const UPDATE_NEW_ASSET = 'property/UPDATE_NEW_ASSET';
export const ADD_ASSET = 'property/ADD_ASSET';

export const TOGGLE_MANAGE_PROPERTY_MODAL = 'property/OPEN_MANAGE_PROPERTY_MODAL';
export const UPDATE_MANAGE_PROPERTY = 'property/UPDATE_MANAGE_PROPERTY';
export const UPDATE_MANAGE_PROPERTY_AMENITIES = 'property/UPDATE_MANAGE_PROPERTY_AMENITIES';
export const UPDATE_MANAGE_PROPERTY_LOCATION = 'property/UPDATE_MANAGE_PROPERTY_LOCATION';
export const UPDATE_MANAGE_PROPERTY_IMAGES = 'property/UPDATE_MANAGE_PROPERTY_IMAGES';
export const SAVE_PROPERTY = 'property/SAVE_PROPERTY';